// Advanced algebra question generators
window.MG = window.MG || {};
MG.generators = MG.generators || [];

(function () {
	const F = MG.fmt, G = MG.generators;
	const num = (value, label = 'x', tolerance = 0.001) => ({ type: 'numeric', value, tolerance, label });
	const multi = (values, labels, tolerance = 0.001) => ({ type: 'multinumeric', values, labels, tolerance });
	const txt = (accept, placeholder = 'Enter an exact algebraic expression') => ({ type: 'text', accept, placeholder });
	const mc = (r, correct, wrongs) => { const a = r.shuffle([correct, ...wrongs]); return { type: 'mc', choices: a, correct: a.indexOf(correct) }; };
	const add = (id, subtopic, difficulty, builders) => G.push({ id, topic: 'Algebra', subtopic, difficulty, gen(r) { return r.pick(builders)(r); } });
	const sol = (lines, answer) => lines.map(x => `<p>${x}</p>`).join('') + `<p><strong>${answer}</strong></p>`;
	const signed = n => n < 0 ? ` &minus; ${-n}` : ` + ${n}`;
	const fracKey = (a, b) => { const g = MG.gcd(Math.abs(a), Math.abs(b)), s = b < 0 ? -1 : 1; return `${s * a / g}/${s * b / g}`; };

	add('alg-abs-linear', 'Absolute-value inequalities', 2, [
		r => { const a=r.pick([2,3,4]),h=r.int(-3,3),c=a*r.int(1,3),lo=h-c/a,hi=h+c/a,strict=r.pick([true,false]); return {marks:5,text:`Solve |${a}(x${signed(-h)})| ${strict?'&lt;':'&le;'} ${c}. Give the exact interval endpoints.`,answer:multi([lo,hi],['lower endpoint (exact)','upper endpoint (exact)']),solution:sol([`This is ${strict?'&minus;':'&minus;'}${c} ${strict?'&lt;':'&le;'} ${a}(x${signed(-h)}) ${strict?'&lt;':'&le;'} ${c}.`,`Divide by ${a} and add ${h}.`],`${lo} ${strict?'&lt;':'&le;'} x ${strict?'&lt;':'&le;'} ${hi}`)}; },
		r => { const a=r.pick([2,3]),h=r.int(-2,2),c=a*r.int(1,3),lo=h-c/a,hi=h+c/a; return {marks:4,text:`Find the two boundary points of |${a}x${signed(-a*h)}| &gt; ${c}, and state which region is selected.`,answer:multi([lo,hi],['left boundary (exact)','right boundary (exact)']),solution:sol([`First solve ${a}(x${signed(-h)})=&plusmn;${c}.`,`Because the absolute value is greater than ${c}, select the two exterior regions.`],`x &lt; ${lo} or x &gt; ${hi}`)}; }
	]);
	add('alg-abs-compared', 'Absolute-value inequalities', 2, [
		r => { const p=r.int(-3,1),q=r.int(p+1,3),m=r.pick([2,3]); return {marks:5,text:`Solve |x${signed(-p)}| &lt; |${m}x${signed(-m*q)}|. Enter the two exact boundary points in increasing order.`,answer:multi([(m*q-p)/(m-1),(m*q+p)/(m+1)].sort((a,b)=>a-b),['lower boundary (exact)','upper boundary (exact)']),solution:sol([`Square both non-negative sides and use A${F.sup(2)}&minus;B${F.sup(2)}=(A-B)(A+B).`,`The signs alternate across the two resulting linear-factor zeros; test one point in each interval.`],`Select the intervals where the product is negative.`)}; },
		r => { const p=r.int(-3,0),q=r.int(1,3),m=r.pick([2,4]); const e=[(m*q-p)/(m-1),(m*q+p)/(m+1)].sort((a,b)=>a-b); return {marks:5,text:`Determine the boundary values for |x${signed(-p)}| &le; |${m}(x${signed(-q)})|. Give exact values.`,answer:multi(e,['smaller boundary (exact)','larger boundary (exact)']),solution:sol([`Squaring is equivalent because both sides are non-negative.`,`Factor the difference of squares and make a sign table.`],`The endpoints are ${MG.fracReduced(Math.round(e[0]*1000),1000)} and ${MG.fracReduced(Math.round(e[1]*1000),1000)}.`)}; }
	]);
	add('alg-rational-inequality', 'Rational inequalities', 2, [
		r => { const excluded=r.int(-3,3),c=r.pick([2,3]); let zero=r.int(-3,3); if(zero===excluded)zero=excluded===3?-3:excluded+1; const a=(c-1)*zero-c*excluded; return {marks:5,text:`Solve ${F.frac(`x${signed(a)}`,`x${signed(-excluded)}`)} &ge; ${c}. Enter the critical points in increasing order; one is excluded.`,answer:multi([zero,excluded].sort((x,y)=>x-y),['smaller critical point (exact)','larger critical point (exact)']),solution:sol([`Bring ${c} to the left: the numerator simplifies to ${(1-c)}(x${signed(-zero)}).`,`The denominator is zero at x=${excluded}; mark it with an open point. Make a sign table.`],`Critical points: ${Math.min(zero,excluded)}, ${Math.max(zero,excluded)}; x=${excluded} is excluded.`)}; },
		r => { const e=r.int(-3,3),z=e===3?-2:e+1,c=r.pick([-2,-1]); const a=(c-1)*z-c*e; return {marks:4,text:`For ${F.frac(`x${signed(a)}`,`x${signed(-e)}`)} &lt; ${c}, find both exact sign-chart breakpoints and identify the excluded one.`,answer:multi([e,z].sort((x,y)=>x-y),['lower breakpoint (exact)','upper breakpoint (exact)']),solution:sol([`Combine over the original denominator. The numerator has zero x=${z}.`,`The original denominator excludes x=${e}; test the three intervals.`],`Breakpoints ${Math.min(e,z)}, ${Math.max(e,z)}; excluded: ${e}.`)}; }
	]);
	add('alg-exponential-powers', 'Exponential equations', 2, [
		r => { const k=r.int(-3,3),n=r.pick([2,3]),x=(3*k+n)/(3*n); return {marks:4,text:`Solve exactly: 2${F.sup(`x + ${n}`)}&middot;4${F.sup(`x &minus; ${n}`)} = 8${F.sup(k)}.`,answer:txt([fracKey(3*k+n,3*n),String(x)]),solution:sol([`Write every term in base 2: the left exponent is (x+${n})+2(x&minus;${n})=3x&minus;${n}.`,`Equate exponents: 3x&minus;${n}=3(${k}).`],`x=${MG.fracReduced(3*k+n,3*n)}`)}; },
		r => { const k=r.int(-3,3),n=r.pick([1,2,3]),x=(2*k+3*n)/4; return {marks:4,text:`Find the exact solution of 9${F.sup(`x &minus; ${n}`)}&middot;3${F.sup('2x')} = 27${F.sup(k)}.`,answer:txt([fracKey(2*k+3*n,4),String(x)]),solution:sol([`Convert to base 3: 2(x&minus;${n})+2x=3${k}.`,`Hence 4x=3${n}+3${k}.`],`x=${MG.fracReduced(3*(n+k),4)}`)}; }
	]);
	add('alg-log-quadratic', 'Logarithmic equations', 2, [
		r => { const base=r.pick([2,3,5]),p=r.int(1,3),q=r.int(1,3),root=r.int(1,3),product=(root+p)*(root+q),rhs=Math.round(Math.log(product)/Math.log(base)); const x=Math.sqrt(base**rhs+(p-q)**2/4)-(p+q)/2; return {marks:5,text:`Solve log${F.sub(base)}(x + ${p}) + log${F.sub(base)}(x + ${q}) = ${rhs}. Give the valid answer correct to 2 decimal places and reject the extraneous root.`,answer:num(MG.round(x,2),'valid x (2 d.p.)',0.01),solution:sol([`Domain: x&gt;${-Math.min(p,q)}. Combine logs to get (x+${p})(x+${q})=${base**rhs}.`,`Solve the quadratic. Its negative root fails the domain restriction.`],`x=${MG.round(x,2)} (2 d.p.)`)}; },
		r => { const base=r.pick([2,3]),p=r.int(1,3),q=r.int(1,3),root=r.int(1,3),rhs=Math.round(Math.log((root+p)*(root+q))/Math.log(base)); const D=(p-q)**2+4*base**rhs,x=(-(p+q)+Math.sqrt(D))/2; return {marks:5,text:`Use log laws to solve log${F.sub(base)}(x + ${p}) + log${F.sub(base)}(x + ${q}) = ${rhs}, correct to 2 decimal places. Show why the other quadratic root is rejected.`,answer:num(MG.round(x,2),'x (2 d.p.)',0.01),solution:sol([`The equation becomes x${F.sup(2)}+${p+q}x+${p*q-base**rhs}=0, with both log arguments positive.`,`The second root is outside that common domain.`],`x=${MG.round(x,2)} (2 d.p.)`)}; }
	]);
	add('alg-subject-exponential', 'Changing the subject', 2, [
		r => { const tv=r.pick(['t','n','u','w']),m=r.pick([2,3,5]); const form=r.pick([`A = P&middot;e<sup>${m}k${tv}</sup>`,`N = N<sub>0</sub>e<sup>&minus;${m}k${tv}</sup>`]); const growing=form[0]==='A'; const correct=growing?`k = ln(A/P)/(${m}${tv})`:`k = ln(N₀/N)/(${m}${tv})`; return {marks:4,text:`Make k the subject of ${form}. Assume all quantities needed by the logarithm are positive.`,answer:mc(r,correct,growing?[`k = ${m}${tv} ln(A/P)`,`k = ln(P/A)/(${m}${tv})`,`k = ${m} ln(A/P)/${tv}`]:[`k = ln(N/N₀)/(${m}${tv})`,`k = ${m}${tv} ln(N₀/N)`,`k = ${m} ln(N₀/N)/${tv}`]),solution:sol([`Divide by the initial quantity, then take natural logarithms.`,`Finally divide by ${m}${tv}, taking care of the negative exponent.`],correct)}; },
		r => { const tv=r.pick(['t','n','m','s']),b=r.pick(['b','a','g']),m=r.pick([2,3,4]); const correct=`k = ln(Q/C)/(${m}${tv} ln ${b})`; return {marks:4,text:`Given Q = C${b}${F.sup(`${m}k${tv}`)}, make k the subject (${b}&gt;0, ${b}&ne;1).`,answer:mc(r,correct,[`k = ln(Q/C) ln ${b}/(${m}${tv})`,`k = ${m}${tv} ln(Q/C)/ln ${b}`,`k = ln(C/Q)/(${m}${tv} ln ${b})`]),solution:sol([`Q/C=${b}${F.sup(`${m}k${tv}`)}. Taking logs gives ln(Q/C)=${m}k${tv} ln ${b}.`,`Divide by ${m}${tv} ln ${b}.`],correct)}; }
	]);
	add('alg-surd-rationalise', 'Surds', 2, [
		r => { const d=r.pick([2,3,5]),c=r.int(2,4),a=r.int(1,3),b=d,den=c*c-d,A=(a*c+b*d)/den,B=(a+b*c)/den; return {marks:5,text:`Rationalise and simplify ${F.frac(`${a} + ${b}${F.sqrt(d)}`,`${c} &minus; ${F.sqrt(d)}`)}. Enter the rational coefficient and the coefficient of ${F.sqrt(d)}.`,answer:multi([A,B],['rational part (exact)','surd coefficient (exact)']),solution:sol([`Multiply by the conjugate ${c}+${F.sqrt(d)}. The denominator is ${den}.`,`Expanding the numerator and collecting rational and surd terms gives the result.`],`${MG.fracReduced(a*c+b*d,den)} + ${MG.fracReduced(a+b*c,den)}${F.sqrt(d)}`)}; },
		r => { const d=r.pick([2,3]),c=r.pick([2,3]),a=r.int(1,3),b=r.int(1,3),den=c*c-d,A=(a*c+b*d)/den,B=(a+b*c)/den; return {marks:5,text:`Write ${F.frac(`${a} + ${b}${F.sqrt(d)}`,`${c} &minus; ${F.sqrt(d)}`)} in the exact form u + v${F.sqrt(d)}. Enter u and v.`,answer:multi([A,B],['u (exact)','v (exact)']),solution:sol([`Use the conjugate ${c}+${F.sqrt(d)} and denominator ${c*c}&minus;${d}.`,`Collect the rational and ${F.sqrt(d)} parts separately.`],`u=${MG.fracReduced(a*c+b*d,den)}, v=${MG.fracReduced(a+b*c,den)}`)}; }
	]);
	add('alg-linear-quadratic', 'Simultaneous equations', 2, [
		r => { const p=r.int(-3,0),q=r.int(1,3),m=p+q,b=-p*q; return {marks:5,text:`Find both intersections of y=x${F.sup(2)} and y=${m}x${signed(b)}. Enter x-coordinates first, then y-coordinates.`,answer:multi([p,q,p*p,q*q],['smaller x','larger x','y at smaller x','y at larger x']),solution:sol([`Equate the equations: x${F.sup(2)}&minus;${m}x${signed(-b)}=0.`,`Factor as (x&minus;${p})(x&minus;${q}) and substitute each x-value.`],`${F.pt(p,p*p)} and ${F.pt(q,q*q)}`)}; },
		r => { const p=r.int(-3,-1),q=r.int(1,3),h=r.int(-2,2),m=p+q-2*h,b=(p-h)*(q-h); return {marks:5,text:`Solve simultaneously y=(x${signed(-h)})${F.sup(2)} and y=${m}x${signed(b)}. Enter the two ordered pairs by increasing x.`,answer:multi([p,p*p+m*p+b-(p*p),q,q*q+m*q+b-(q*q)],['x₁','y₁','x₂','y₂']),solution:sol([`Equating and expanding produces a quadratic with roots ${p} and ${q}.`,`Back-substitute each root into the line.`],`The x-values are ${p} and ${q}.`)}; }
	]);
	add('alg-log-inequality-chain', 'Logarithmic equations', 3, [
		r => { const b=r.pick([2,3,5]),p=r.int(1,3),root=r.int(1,3),R=(root+p)*root,k=Math.round(Math.log(R)/Math.log(b)); const good=(-p+Math.sqrt(p*p+4*b**k))/2,correct=`x &gt; ${MG.round(good,2)}`; return {marks:7,text:`(i) Solve log${F.sub(b)}x + log${F.sub(b)}(x + ${p}) = ${k}, correct to 2 decimal places. (ii) Hence solve log${F.sub(b)}[x(x + ${p})] &gt; ${k}.`,answer:mc(r,correct,[`x &lt; ${MG.round(good,2)}`,`x &ge; ${MG.round(good,2)}`,`0 &lt; x &lt; ${MG.round(good,2)}`]),solution:sol([`The domain is x&gt;0. Part (i) gives x(x+${p})=${b**k}; solve the quadratic and reject its negative root.`,`On x&gt;0, x(x+${p}) is increasing, so the strict logarithmic inequality lies above the valid boundary.`],correct)}; },
		r => { const b=r.pick([2,3]),p=r.int(1,3),k=r.int(2,4),root=(-p+Math.sqrt(p*p+4*b**k))/2,correct=`x &gt; ${MG.round(root,2)}`; return {marks:7,text:`(i) Solve log${F.sub(b)}[x(x + ${p})] = ${k}, correct to 2 decimal places, respecting the domain x&gt;0. (ii) Hence choose the solution of log${F.sub(b)}[x(x + ${p})] &gt; ${k}.`,answer:mc(r,correct,[`x &lt; ${MG.round(root,2)}`,`x &le; ${MG.round(root,2)}`,`0 &lt; x &lt; ${MG.round(root,2)}`]),solution:sol([`Exponentiating gives x${F.sup(2)}+${p}x&minus;${b**k}=0. Only the positive root is in the stated domain.`,`Both the logarithm and the quadratic argument are increasing there.`],correct)}; }
	]);
	add('alg-rational-chain', 'Rational inequalities', 3, [
		r => { const a=r.int(1,3),b=r.int(1,3),p=r.int(-3,3),q=p===3?-2:p+1; return {marks:7,text:`(i) Solve ${F.frac(a,`x${signed(-p)}`)} = ${F.frac(b,`x${signed(-q)}`)} exactly. (ii) State both restrictions and determine where the left side exceeds the right side. Enter the restrictions.`,answer:multi([p,q].sort((x,y)=>x-y),['smaller excluded value','larger excluded value']),solution:sol([`Restrictions are x&ne;${p},${q}. Cross-multiplication gives a linear equation for the equality boundary.`,`Put all terms over the common denominator and use a sign chart including both excluded values.`],`Excluded values: ${Math.min(p,q)}, ${Math.max(p,q)}.`)}; },
		r => { const p=r.int(-3,0),q=r.int(1,3); return {marks:6,text:`(i) Simplify ${F.frac(`x${signed(-p)}`,`x${signed(-q)}`)} &minus; 1. (ii) Hence solve when the original fraction is at least 1. Enter the zero and excluded point in increasing order.`,answer:multi([p,q].sort((x,y)=>x-y),['smaller critical value','larger critical value']),solution:sol([`Combining with 1 gives ${q-p}/(x${signed(-q)}). Retain x&ne;${q}.`,`Use the sign of this expression for the inequality.`],`Critical values ${Math.min(p,q)}, ${Math.max(p,q)}; ${q} is excluded.`)}; }
	]);
	add('alg-exp-log-identity', 'Exponential and logarithmic equations', 3, [
		r => { const a=r.pick([2,3]),b=r.pick([4,5,6]),y=r.pick([2,3,5]),x=Math.exp((Math.log(b)**2-Math.log(a)**2)/(Math.log(a)-Math.log(b))); return {marks:7,text:`Solve ( ${a}x )${F.sup(`log${F.sub(y)} ${a}`)} = ( ${b}x )${F.sup(`log${F.sub(y)} ${b}`)}. Give x correct to 3 significant figures.`,answer:num(Number(x.toPrecision(3)),'x (3 significant figures)',0.01),solution:sol([`Take natural logs and use log${F.sub(y)}z=ln z/ln ${y}.`,`After multiplying by ln ${y}, expand and collect ln x. This gives ln x=&minus;(ln ${a}+ln ${b}).`],`x=${Number(x.toPrecision(3))} (3 significant figures)`)}; },
		r => { const a=r.pick([2,4]),b=r.pick([3,5,6]),y=r.pick([2,3,7]),x=1/(a*b); return {marks:6,text:`By taking logarithms, solve (${a}x)${F.sup(`log${F.sub(y)} ${a}`)} = (${b}x)${F.sup(`log${F.sub(y)} ${b}`)}. Give an exact answer.`,answer:txt([`1/${a*b}`,`1/(${a*b})`]),solution:sol([`Taking logs and applying change of base yields ln a(ln a+ln x)=ln b(ln b+ln x).`,`Factor (ln a&minus;ln b); since a&ne;b, ln x=&minus;ln a&minus;ln b.`],`x=${F.frac(1,a*b)}`)}; }
	]);
	add('alg-subject-log', 'Changing the subject', 3, [
		r => { const a=r.pick([2,3,5]),m=r.pick([2,3]),[cv,dv]=r.pick([['c','d'],['p','q'],['w','v']]),correct=`k = ${a}^((${cv} − ${dv})/${m})`; return {marks:6,text:`Make k the subject of ${cv} = ${m}log${F.sub(a)}k + ${dv}, with k&gt;0.`,answer:mc(r,correct,[`k = ${a}^(${cv} − ${dv})/${m}`,`k = log_${a}((${cv} − ${dv})/${m})`,`k = ${a}^(${m}(${cv} − ${dv}))`]),solution:sol([`Subtract ${dv} and divide by ${m}: log${F.sub(a)}k=(${cv}&minus;${dv})/${m}.`,`Convert from logarithmic to exponential form.`],correct)}; },
		r => { const m=r.pick([2,3,4]),[uv,vv]=r.pick([['u','v'],['a','b'],['s','c']]),correct=`k = exp((${uv} − ${vv})/${m})`; return {marks:6,text:`Given ${uv} = ${m} ln k + ${vv}, make k the subject and state its natural domain.`,answer:mc(r,correct,[`k = ln((${uv} − ${vv})/${m})`,`k = exp(${m}(${uv} − ${vv}))`,`k = exp(${uv} − ${vv})/${m}`]),solution:sol([`ln k=(${uv}&minus;${vv})/${m}.`,`Exponentiate both sides; necessarily k&gt;0.`],correct)}; }
	]);
})();

MG.polyKey = MG.polyKey || function (coeffs) {
	const n=coeffs.length-1; let out='';
	coeffs.forEach((c,i)=>{ if(!c)return; const p=n-i,v=p===0?'':p===1?'x':`x^${p}`,a=Math.abs(c),term=v?(a===1?v:a+v):String(a); out+=out===''?(c<0?'-'+term:term):(c>0?'+':'-')+term; });
	return out||'0';
};
