window.MG = window.MG || {};
MG.generators = MG.generators || [];
(function () {
	const F = MG.fmt, G = MG.generators;
	const br = (i, s) => `<br><strong>(${i})</strong> ${s}`;
	const boss = (id, subtopic, gen) => G.push({ id, topic: 'Boss', subtopic, difficulty: 4, gen });
	const multi = (values, labels, tolerance) => ({ type: 'multinumeric', values, labels, tolerance });
	const rad = MG.degToRad;

	boss('exam-log-chain', 'Logarithms + Exponential equations', (r) => {
		const base = r.pick([2, 3, 4, 5]), x = r.int(3, 7), shift = r.int(1, 5), arg = base ** x, evalBase = r.pick([6, 7, 8, 10]), evalArg = r.int(31, 97), cv = MG.round(Math.log(evalArg) / Math.log(evalBase), 2), initial = r.int(180, 640), rate = r.pick([1.07, 1.09, 1.12, 1.15]), target = r.int(2, 4) * initial + r.int(7, 29), t = MG.round(Math.log(target / initial) / Math.log(rate), 2), amount = MG.round(initial * rate ** cv, 2);
		return { marks: 7, text: `<p>A student links logarithms to an exponential-growth model. The model data are:</p><table class="qtable"><tr><th>Initial quantity</th><th>Growth factor</th><th>Target</th></tr><tr><td>${initial}</td><td>${rate}</td><td>${target}</td></tr></table>${br('i', `Solve log${F.sub(base)}(y + ${shift}) = ${x}.`)}${br('ii', `Use change of base to evaluate log${F.sub(evalBase)}${evalArg}, correct to 2 d.p.`)}${br('iii', `For A=${initial}(${rate})${F.sup('t')}, find A when t equals your answer to (ii), correct to 2 d.p.`)}${br('iv', 'Find when the model first reaches the target, correct to 2 d.p.')}`, answer: multi([arg - shift, cv, amount, t], ['y', 'logarithm (2 d.p.)', 'model amount (2 d.p.)', 'time (2 d.p.)'], .01), solution: `<p><strong>(i)</strong> y+${shift}=${base}${F.sup(x)}=${arg}, so <strong>y=${arg - shift}</strong>.</p><p><strong>(ii)</strong> Change of base gives log(${evalArg})/log(${evalBase})=<strong>${cv}</strong>.</p><p><strong>(iii)</strong> Substitution gives ${initial}(${rate})${F.sup(cv)}=<strong>${amount}</strong>.</p><p><strong>(iv)</strong> Solving ${target}/${initial}=${rate}${F.sup('t')} gives t=log(${target}/${initial})/log(${rate})=<strong>${t}</strong>.</p>` };
	});

	boss('exam-polynomial-chain', 'Remainder theorem + Factorisation', (r) => {
		const roots = r.shuffle([r.int(-6, -2), r.int(1, 4), r.int(5, 9)]), a = roots[0], b = roots[1], c = roots[2], q = a * b + a * c + b * c, d = -a * b * c, k = -(a + b + c), rem = a ** 3 + k * a ** 2 + q * a + d, sum = -k;
		const product = a * b * c;
		return { marks: 7, text: `<p>Let P(x)=x${F.sup(3)}+kx${F.sup(2)}${F.st(q, 'x')}${F.st(d, '')}, and suppose (x${F.st(-a, '')}) is a factor.</p><table class="qtable"><tr><th>Divisor</th><th>Condition</th></tr><tr><td>x${F.st(-a, '')}</td><td>remainder zero</td></tr></table>${br('i', `Use the remainder theorem to determine P(${a}) and hence find k.`)}${br('ii', 'Factor P(x) fully and find the sum of its roots.')}${br('iii', 'Without expanding the factors, find the product of the three roots.')}`, answer: multi([rem, k, sum, product], ['remainder', 'k', 'sum of roots', 'product of roots'], .001), solution: `<p><strong>(i)</strong> Substitution and the factor condition give P(${a})=<strong>${rem}</strong>, then <strong>k=${k}</strong>.</p><p><strong>(ii)</strong> P(x)=(x${F.st(-a, '')})(x${F.st(-b, '')})(x${F.st(-c, '')}), so the sum is <strong>${sum}</strong>.</p><p><strong>(iii)</strong> Multiplying the roots gives <strong>${product}</strong>.</p>` };
	});

	boss('exam-transform-chain', 'Graph transformations + Quadratics', (r) => {
		const h = r.int(-5, 5), k = r.int(-5, 3), dx = r.nonzeroInt(-4, 4), spread = r.int(2, 6), nh = h + dx, nk = -(spread ** 2), actualDy = nk - k, left = nh - spread, right = nh + spread;
		return { marks: 6, text: `<p>The parabola f(x)=(x${F.st(-h, '')})${F.sup(2)}${F.st(k, '')} is translated ${Math.abs(dx)} units ${dx > 0 ? 'right' : 'left'} and an unknown number of units vertically to form g.</p>${br('i', 'State the vertex of f.')}${br('ii', `The translated graph has vertex y-coordinate ${nk}. Find the vertical translation.`)}${br('iii', 'Hence find both x-intercepts of g, in ascending order.')}`, answer: multi([h, k, actualDy, left, right], ['vertex x', 'vertex y', 'vertical shift', 'smaller intercept', 'larger intercept'], .001), solution: `<p><strong>(i)</strong> Vertex form gives <strong>(${h}, ${k})</strong>.</p><p><strong>(ii)</strong> The new vertex is (${nh},${nk}), so the vertical translation is ${nk}&minus;(${k})=<strong>${actualDy}</strong>.</p><p><strong>(iii)</strong> g(x)=(x${F.st(-nh, '')})&sup2;&minus;${spread ** 2}. Setting g=0 gives x=${nh}&plusmn;${spread}, hence <strong>${left}, ${right}</strong>.</p>` };
	});

	boss('exam-probability-chain', 'Without replacement + Conditional probability', (r) => {
		const red = r.int(5, 12), blue = r.int(4, 11), n = red + blue, sameExact = (red * (red - 1) + blue * (blue - 1)) / (n * (n - 1)), atLeastExact = 1 - blue * (blue - 1) / (n * (n - 1)), differentExact = 2 * red * blue / (n * (n - 1)), same = MG.round(sameExact, 4), atLeastRed = MG.round(atLeastExact, 4), cond = MG.round(differentExact / atLeastExact, 4), arrangements = red * blue * 2;
		return { marks: 7, text: `<p>A bag contains ${red} red and ${blue} blue counters. Two distinct counters are drawn in order without replacement.</p>${br('i', 'Using counting, find the number of ordered selections having different colours.')}${br('ii', 'Find P(the counters have the same colour), correct to 4 d.p.')}${br('iii', 'Hence find P(at least one red), correct to 4 d.p.')}${br('iv', 'Given that at least one is red, find P(the colours differ), correct to 4 d.p.')}`, answer: multi([arrangements, same, atLeastRed, cond], ['ordered different-colour selections', 'P(same) (4 d.p.)', 'P(at least one red) (4 d.p.)', 'conditional probability (4 d.p.)'], .0005), diagram: { type: 'tree2', stage1: [{ label: 'R', prob: `${red}/${n}` }, { label: 'B', prob: `${blue}/${n}` }], stage2: [[{ label: 'R', prob: `${red - 1}/${n - 1}` }, { label: 'B', prob: `${blue}/${n - 1}` }], [{ label: 'R', prob: `${red}/${n - 1}` }, { label: 'B', prob: `${blue - 1}/${n - 1}` }]] }, solution: `<p><strong>(i)</strong> There are ${red}&times;${blue} choices in each colour order, giving <strong>${arrangements}</strong>.</p><p><strong>(ii)</strong> Adding the RR and BB paths gives <strong>${same}</strong>.</p><p><strong>(iii)</strong> 1&minus;P(BB)=<strong>${atLeastRed}</strong>.</p><p><strong>(iv)</strong> P(RB or BR)/P(at least one R)=<strong>${cond}</strong>.</p>` };
	});

	boss('exam-bearings-chain', 'Bearings + Cosine rule', (r) => {
		const b1 = r.pick([25, 40, 55, 70]), turn = r.pick([65, 80, 100, 115]), b2 = b1 + turn, d1 = r.int(8, 25), d2 = r.int(8, 25), inside = 180 - turn, home = MG.round(Math.sqrt(d1 ** 2 + d2 ** 2 - 2 * d1 * d2 * Math.cos(rad(inside))), 2), east = d1 * Math.sin(rad(b1)) + d2 * Math.sin(rad(b2)), north = d1 * Math.cos(rad(b1)) + d2 * Math.cos(rad(b2)), bearing = MG.round((Math.atan2(-east, -north) * 180 / Math.PI + 360) % 360, 0);
		return { marks: 6, text: `<p>A ${r.pick(['rescue boat', 'survey vessel', 'patrol craft'])} travels ${d1} km on bearing ${b1}&deg;, then ${d2} km on bearing ${b2}&deg;.</p>${br('i', 'Find the included angle at the turning point.')}${br('ii', 'Hence find the direct distance back to the start, correct to 2 d.p.')}${br('iii', 'Hence, or otherwise, find the bearing back to the start, to the nearest degree.')}`, answer: multi([inside, home, bearing], ['included angle', 'distance (2 d.p.)', 'bearing (nearest degree)'], .5), diagram: { type: 'bearings', legs: [{ bearing: b1, dist: d1, label: `${d1} km` }, { bearing: b2, dist: d2, label: `${d2} km` }] }, solution: `<p><strong>(i)</strong> Comparing the second bearing with the first leg's back-bearing gives <strong>${inside}&deg;</strong>.</p><p><strong>(ii)</strong> Cosine rule gives d=&radic;[${d1}&sup2;+${d2}&sup2;&minus;2(${d1})(${d2})cos ${inside}&deg;]=<strong>${home} km</strong>.</p><p><strong>(iii)</strong> Resolving each leg north and east, then reversing the resultant, gives <strong>${bearing}&deg;</strong>.</p>` };
	});

	boss('exam-optimisation-chain', 'Quadratic modelling + Optimisation', (r) => {
		const length = r.pick([36, 40, 44, 48, 52, 56]), half = length / 2, x = half / 2, area = x * (length - 2 * x), test = r.int(3, 8), testArea = test * (length - 2 * test);
		return { marks: 6, text: `<p>${length} m of fencing forms three sides of a rectangular enclosure against a straight wall. Let each perpendicular side be x metres.</p><table class="qtable"><tr><th>x (m)</th><th>parallel side (m)</th></tr><tr><td>${test}</td><td>${length - 2 * test}</td></tr></table>${br('i', `Find the area when x=${test} m.`)}${br('ii', 'Hence write the area as a quadratic in x and find the value of x that maximises it.')}${br('iii', 'Find the maximum area.')}`, answer: multi([testArea, x, area], ['test area', 'x at maximum', 'maximum area'], .001), solution: `<p><strong>(i)</strong> A=${test}(${length}&minus;2(${test}))=<strong>${testArea} m&sup2;</strong>.</p><p><strong>(ii)</strong> A=&minus;2x&sup2;+${length}x, whose vertex gives <strong>x=${x} m</strong>.</p><p><strong>(iii)</strong> Substitution gives <strong>${area} m&sup2;</strong>.</p>` };
	});

	boss('exam-circle-locus-chain', 'Loci + Circles + Tangents', (r) => {
		const h = r.int(-5, 5), k = r.int(-5, 5), radius = r.int(2, 3), C = h * h + k * k - radius * radius, lineC = radius - h, dist = Math.abs(h + lineC), tangent = dist === radius ? 1 : 0;
		return { marks: 6, text: `<p>A circle has equation x&sup2;+y&sup2;${F.st(-2 * h, 'x')}${F.st(-2 * k, 'y')}${F.st(C, '')}=0.</p>${br('i', 'Find the coordinates of its centre.')}${br('ii', 'Hence find its radius.')}${br('iii', `The line x${F.st(lineC, '')}=0 is proposed as a tangent. Check the perpendicular distance and enter 1 if it is tangent, or 0 if it is not.`)}`, answer: multi([h, k, radius, tangent], ['centre x', 'centre y', 'radius', 'tangent: 1=yes, 0=no'], .001), solution: `<p><strong>(i)</strong> Completing squares gives centre <strong>(${h}, ${k})</strong>.</p><p><strong>(ii)</strong> The squared radius is ${radius ** 2}, hence <strong>r=${radius}</strong>.</p><p><strong>(iii)</strong> Distance to the vertical line is |${h}${F.st(lineC, '')}|=<strong>${dist}</strong>. This equals the radius, so the line is tangent: <strong>1</strong>.</p>` };
	});

	boss('exam-trig-chain', 'Trigonometric identities + Equations', (r) => {
		const value = r.pick([0.25, 0.4, 0.5, 0.6, 0.75]), alpha = Math.asin(value) * 180 / Math.PI, a1 = MG.round(alpha, 0), a2 = MG.round(180 - alpha, 0), check = MG.round(1 - value ** 2, 4);
		return { marks: 6, text: `<p>In a ${r.pick(['navigation calculation', 'surveying exercise', 'trigonometry investigation'])}, use sin&sup2;&theta;+cos&sup2;&theta;=1.</p>${br('i', `Given sin &theta;=${value}, find cos&sup2;&theta;, correct to 4 d.p.`)}${br('ii', `Hence solve sin x=${value} for 0&deg;&le;x&le;180&deg;, giving answers to the nearest degree.`)}${br('iii', 'Hence find the positive difference between the two solutions, to the nearest degree.')}`, answer: multi([check, a1, a2, a2 - a1], ['cos squared (4 d.p.)', 'smaller x (nearest degree)', 'larger x (nearest degree)', 'difference (nearest degree)'], .5), solution: `<p><strong>(i)</strong> cos&sup2;&theta;=1&minus;sin&sup2;&theta;=1&minus;${value}&sup2;=<strong>${check}</strong>.</p><p><strong>(ii)</strong> The reference angle is sin${F.sup('&minus;1')}(${value})=${F.num(alpha, 2)}&deg;. Sine is positive in quadrants I and II, giving <strong>${a1}&deg;, ${a2}&deg;</strong>.</p><p><strong>(iii)</strong> The positive difference is ${a2}&minus;${a1}=<strong>${a2 - a1}&deg;</strong>.</p>` };
	});

	boss('exam-inequality-chain', 'Absolute value + Quadratic inequalities', (r) => {
		const a = r.pick([2, 3, 4]), centre = r.int(-4, 5), width = r.int(2, 6), lo = centre - width, hi = centre + width, count = hi - lo + 1, qlo = lo - r.int(1, 4), qhi = hi - r.int(0, 2), combinedLo = Math.max(lo, qlo), combinedHi = Math.min(hi, qhi), combinedCount = Math.max(0, combinedHi - combinedLo + 1);
		return { marks: 7, text: `<p>Consider the inequality |${a}x${F.st(-a * centre, '')}|&le;${a * width}.</p>${br('i', 'Find the lower and upper endpoints of its solution interval.')}${br('ii', 'Hence find the number of integers in this interval.')}${br('iii', `Also require (x${F.st(-qlo, '')})(x${F.st(-qhi, '')})&le;0. Find the number of integers satisfying both inequalities.`)}`, answer: multi([lo, hi, count, combinedCount], ['lower endpoint', 'upper endpoint', 'integer count', 'combined integer count'], .001), solution: `<p><strong>(i)</strong> Dividing by ${a} gives |x${F.st(-centre, '')}|&le;${width}, so <strong>${lo}&le;x&le;${hi}</strong>.</p><p><strong>(ii)</strong> The inclusive integer count is ${hi}&minus;(${lo})+1=<strong>${count}</strong>.</p><p><strong>(iii)</strong> The quadratic is non-positive between its roots, so intersecting [${qlo},${qhi}] with [${lo},${hi}] gives [${combinedLo},${combinedHi}], containing <strong>${combinedCount}</strong> integers.</p>` };
	});

	boss('exam-decay-chain', 'Exponential decay + Logarithms', (r) => {
		const item = r.pick(['medicine', 'radioactive sample', 'chemical tracer']), initial = r.int(120, 500), rate = r.pick([0.72, 0.78, 0.82, 0.86, 0.9]), years = r.int(3, 9), amount = MG.round(initial * rate ** years, 2), half = MG.round(Math.log(.5) / Math.log(rate), 2), target = r.pick([.2, .25, .3]) * initial, time = MG.round(Math.log(target / initial) / Math.log(rate), 2);
		return { marks: 6, text: `<p>The amount of a ${item} is modelled by A=${initial}(${rate})${F.sup('t')}, where t is measured in hours.</p><table class="qtable"><tr><th>Initial amount</th><th>Hourly multiplier</th><th>Threshold</th></tr><tr><td>${initial}</td><td>${rate}</td><td>${target}</td></tr></table>${br('i', `Find A after ${years} hours, correct to 2 d.p.`)}${br('ii', 'Hence find the half-life, correct to 2 d.p.')}${br('iii', 'Find when A first reaches the threshold, correct to 2 d.p.')}`, answer: multi([amount, half, time], ['amount (2 d.p.)', 'half-life (2 d.p.)', 'time (2 d.p.)'], .01), solution: `<p><strong>(i)</strong> A=${initial}(${rate})${F.sup(years)}=<strong>${amount}</strong>.</p><p><strong>(ii)</strong> 0.5=${rate}${F.sup('t')}, so <strong>t=${half} h</strong>.</p><p><strong>(iii)</strong> Solving ${target}/${initial}=${rate}${F.sup('t')} gives <strong>t=${time} h</strong>.</p>` };
	});
})();
